package domainapp.dom.impl;

import java.io.Serializable;
import java.util.StringTokenizer;

public class VehicleProductId implements Serializable {
	public String vehicle_id;
	public String product_id;

	public VehicleProductId() {
	}

	/**
	 * Constructor accepting same input as generated by toString().
	 */
	public VehicleProductId(String value) {
		StringTokenizer token = new StringTokenizer(value, "::");
		token.nextToken();
		this.vehicle_id = token.nextToken();
		this.product_id = token.nextToken();
	}

	public boolean equals(Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof VehicleProductId)) {
			return false;
		}
		VehicleProductId c = (VehicleProductId) obj;

		return vehicle_id.equals(c.vehicle_id) && product_id.equals(c.product_id);
	}

	public int hashCode() {
		return this.vehicle_id.hashCode() ^ this.product_id.hashCode();
	}

	public String toString() {
		// Give output expected by String constructor
		return this.getClass().getName() + "::" + this.vehicle_id + "::" + this.product_id;
	}
}